### ISSUE TITLE
None of your assignments are tagged.

### ISSUE THREAD

**Issue by patilav** [anvitasurapaneni/WebDevSpring2016#1]
Kindly tag your assignments moving on with next assignments.
Please send me an email with the revision link in mail for Assignment 2,3 at patil.av@husky.neu.edu so that I can grade it.

**Comment by anvitasurapaneni** [comment]
Hi Avanti,
I have tagged my assignments but I was not aware that I had to do tag push
to git..
I have done all of them now..
Could you please check them..
Thank you and sorry for the inconvenience.
Anvita surapaneni
